name: CI for HelloWorld

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov
        
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with: 
        repositary: s10196161/DevOpsTesting
        
    - name: Checkout Test Script
      uses: actions/checkout@v2
      with:
        repositary: s10196161/secretDevOpsTEST
        path: tests
        token: ${{ secrets.DEVOPSTESTING}}
        
    - name: Begin Pytest
      run: |
        mv ./tests/*.* ./
        pytest --cov -v --junitxml=report.xml
    - if: ${{failure()}}
      name: Create Issues
      uses: nashmaniac/create-issue-action@v1.1
      with:
        title: Build Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: workflow-failed
        body: workflow failed for commit ${{github.sha}}
